import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
a= {"Title_id":pd.Series([101,102,103,104,105,106,107,108,109,101]),
    "Movie_name":pd.Series(["Bahubali","RRR","Wednesday","Loki","Dj Tillu","The Avengers","The end Game","KGF","Radhe Syam","Uppena"]),
    "Release_year":pd.Series([2013,2014,2015,2016,2017,2018,2019,2020,2021,2022]),
    "Rating":pd.Series([900,700,970,780,800,950,860,980,1000,700]),
    "Duration":pd.Series([180,120,110,100,120,np.nan,130,120,110,140]),
    "Views":pd.Series([800,100,120,np.nan,200,150,180,120,600,840]),
    "Cost":pd.Series([200,180,120,110,200,150,np.nan,300,100,110]),
    }
b=pd.DataFrame(a)
print(b)
print()
print("----The table is created----")
print()
b['Total']=b['Duration']+b['Views']+b['Cost']
print(b)
print()
print(b['Title_id'])
print(b)
print()
print(b.loc[2])
print()
print(b.loc[2][3])
print()
print("----column update----")
print()
b['Views'][0]=180
print(b)
print()
print("----row update----")
print()
b.loc[0,"Movie_name"]="Racha"
print(b)
print()
print("-----column deletion-----")
print()
b.pop('Total')
print(b)
print()
print("----row deletion----")
x=b.drop(9)
print(x)
print()
print(b['Views'].corr(b['Cost']))
print(b['Rating'].corr(b['Duration']))
x=b.isnull()
print("----isnull()----")
print(x)
print()
x=b.notnull()
print("----notnull()----")
print(x)
print()
x=b.fillna(method='bfill')
print(x)
print()
x=b.fillna(method='pad')
print(x)
print()
print("----drop duplicates----")
g=b.drop_duplicates()
plt.scatter(b["Views"],b["Cost"])
plt.xlabel("Total No.Of Views")
plt.ylabel("Total Cost")
plt.colorbar()
plt.title("relation between Views and Cost")
plt.legend('Scale in 1 mm')
plt.show()
plt.bar(b["Views"],b["Cost"])
plt.xlabel("Total No.Of Views")
plt.ylabel("Total Cost")
plt.title("relation between Views and Cost")
plt.legend('Scale in 1 mm')
plt.show()
plt.plot(b["Views"],b["Cost"])
plt.xlabel("Total No.Of Views")
plt.ylabel("Total Cost")
plt.title("relation between Views and Cost")
plt.legend('Scale in 1 mm')
plt.show()